/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static com.sun.corba.se.impl.util.Utility.printStackTrace;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library_mgt.dbclass;

/**
 *
 * @author Big-Blast
 */
public class room_allocation extends javax.swing.JPanel {

    /**
     * Creates new form room_allocation
     */
    public room_allocation() {
        initComponents();
        load_building();
        load_year();
        load_sem();
        load_code();
        load_lecDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(80, 195, 195));

        jLabel2.setText("Subject Code");

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setText("Year");

        jLabel5.setText("Semester");

        jLabel6.setText("Room");

        jTable1.setBackground(new java.awt.Color(80, 195, 195));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecturer", "Subject Code", "Type", "Year", "Semester", "Building", "Room", "Date", "Day", "Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Date");

        jLabel8.setText("Time");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.30 AM", "9.30 AM", "10.30 AM", "11.30 AM", "12.30 PM", "1.30 PM", "2.30 PM", "3.30 PM", "4.30 PM" }));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox10.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox10PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel1.setText("Building");

        jComboBox11.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox11PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox11MouseReleased(evt);
            }
        });

        jLabel3.setText("Lecturer Details");

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseReleased(evt);
            }
        });

        jLabel9.setText("Type");

        jRadioButton1.setBackground(new java.awt.Color(80, 195, 195));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Lecture");

        jRadioButton2.setBackground(new java.awt.Color(80, 195, 195));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tutorial");

        jRadioButton3.setBackground(new java.awt.Color(80, 195, 195));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Laboratory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox3, 0, 174, Short.MAX_VALUE)
                                            .addComponent(jComboBox4, 0, 174, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, 0, 173, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton3))))))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(214, 214, 214)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox11MouseReleased
        
        
    }//GEN-LAST:event_jComboBox11MouseReleased

    private void jComboBox11PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox11PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jComboBox10.removeAllItems();
        load_room();
    }//GEN-LAST:event_jComboBox11PopupMenuWillBecomeInvisible

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat dateformat = new SimpleDateFormat("yyy-MM-dd");
         SimpleDateFormat dateformat2 = new SimpleDateFormat("EEEE");
         jRadioButton1.setActionCommand("Lecture Hall");
         jRadioButton2.setActionCommand("Tutorial");
         jRadioButton3.setActionCommand("Laboratory");
         
      
        String year = jComboBox4.getSelectedItem().toString();
         String semester = jComboBox3.getSelectedItem().toString();
          String type1 = buttonGroup1.getSelection().getActionCommand();
           String sub_code = jComboBox1.getSelectedItem().toString();
            String lec = jComboBox2.getSelectedItem().toString();
            String building = jComboBox11.getSelectedItem().toString();
             String room = jComboBox10.getSelectedItem().toString();
              String theDate = dateformat.format(jDateChooser1.getDate());
               String theDate2 = dateformat2.format(jDateChooser1.getDate());
               String time = jComboBox8.getSelectedItem().toString();
               
        
        System.out.println(theDate2);
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        //dtm.setRowCount(0);
        
        Vector v = new Vector();
        v.add(lec);
        v.add(sub_code);
        v.add(type1);
        v.add(year);
        v.add(semester);
        v.add(building);
        v.add(room);
        v.add(theDate);
        v.add(theDate2);
        v.add(time);
        
        dtm.addRow(v);
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         int lec_id=0,build_id=0;
        if (dtm.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is Empty!!");
        } else {
            String lec, sub_code,type,year,semester,building,room,date,day,time;
            
            try {
     
                for (int i = 0; i < dtm.getRowCount(); i++){
                     lec = dtm.getValueAt(i, 0).toString();
                      sub_code = dtm.getValueAt(i, 1).toString();
                       type = dtm.getValueAt(i, 2).toString();
                        year = dtm.getValueAt(i, 3).toString();
                         semester = dtm.getValueAt(i, 4).toString();
                          building = dtm.getValueAt(i, 5).toString();
                           room = dtm.getValueAt(i, 6).toString();
                            date = dtm.getValueAt(i, 7).toString();
                             day = dtm.getValueAt(i, 8).toString();
                             time = dtm.getValueAt(i, 9).toString();
                            
                            
                ResultSet rs = dbclass.search("SELECT ID FROM lecdetails WHERE LName = '"+lec+"'");
                ResultSet rs1 = dbclass.search("SELECT buildId FROM building WHERE buildname = '"+building+"'");
                
                    if (rs.next() && rs1.next()) {
                    lec_id = Integer.parseInt(rs.getString("ID"));
                    build_id = Integer.parseInt(rs1.getString("buildId"));
                    
                    
                    }
                    dbclass.iud("INSERT INTO time_table(subdetails_Code,location_location_id,room_name,loc_type,lecdetails_ID,year,semester,date,day,time) values('"+sub_code+"','"+build_id+"','"+room+"','"+type+"','"+lec_id+"','"+year+"','"+semester+"','"+date+"','"+day+"','"+time+"')");
                
                }
                JOptionPane.showMessageDialog(null, "Saved Successfully!");
            } catch (Exception e) {
                e.printStackTrace();
            }   
        }
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox10PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox10PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jLabel10.setText("");
        try {
            String value = jComboBox10.getSelectedItem().toString();
            ResultSet rs = dbclass.search("SELECT room_type FROM location WHERE room_name = '"+value+"'");
            while (rs.next()) {                
                String room_type = rs.getString("room_type");
                jLabel10.setText(room_type);
                
                switch (room_type){
                    case "Laboratory":
                        jRadioButton1.setEnabled(false);
                        jRadioButton2.setEnabled(false);
                        jRadioButton3.setEnabled(true);
                        break;
                    case "Lecture Hall":
                        jRadioButton1.setEnabled(true);
                        jRadioButton2.setEnabled(true);
                        jRadioButton3.setEnabled(false);
                        break;
                }
               
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox10PopupMenuWillBecomeInvisible

    private void jDateChooser1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDateChooser1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

private void load_building(){
    try {
        ResultSet rs = dbclass.search("SELECT buildName FROM building");
        while (rs.next()) {            
            String building = rs.getString("buildName");
            jComboBox11.addItem(building);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void load_room(){
    try {
            String value = jComboBox11.getSelectedItem().toString();
            ResultSet rs = dbclass.search("SELECT * FROM building INNER JOIN location ON location.building_buildId = building.buildId WHERE building.buildName = '"+value+"'");
            while (rs.next()) {                
                String room = rs.getString("room_name");
                String room_type = rs.getString("room_type");
                jComboBox10.addItem(room);
                jLabel10.setText(room_type);
            }
        } catch (Exception e) {
            printStackTrace();
        }
}

private void load_year(){
    try {
        ResultSet rs = dbclass.search("SELECT DISTINCT Year FROM subdetails");
        while (rs.next()) {            
            String year = rs.getString("Year");
            jComboBox4.addItem(year);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void load_sem(){
    try {
        ResultSet rs = dbclass.search("SELECT DISTINCT Semester FROM subdetails");
        while (rs.next()) {            
            String semester = rs.getString("Semester");            
            jComboBox3.addItem(semester);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void load_code(){
    try {
        ResultSet rs = dbclass.search("SELECT Code FROM subdetails");
        while (rs.next()) {            
            String sub_code = rs.getString("Code");          
            jComboBox1.addItem(sub_code);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void load_lecDetails(){
     try {
            ResultSet rs = dbclass.search("SELECT LName FROM lecdetails");
            while (rs.next()) {             
             String name = rs.getString("LName");
             jComboBox2.addItem(name);
         }
        } catch (Exception e) {
        }
        
}

}
