/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.ResultSet;
import javax.swing.JFrame;
import library_mgt.dbclass;

/**
 *
 * @author Big-Blast
 */
public class statics extends javax.swing.JFrame {

    lecturer_stat lec = new lecturer_stat();
    subject_stat sub = new subject_stat();
    location_stat loc = new location_stat();
    student_stat stud = new student_stat();
    
    /**
     * Creates new form statics
     */
    public statics() {
        initComponents();
        sub_count();
        lec_count();
        location_count();
        student_count();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lec_button = new javax.swing.JButton();
        subj_button = new javax.swing.JButton();
        stud_button = new javax.swing.JButton();
        loc_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(80, 195, 195));

        l_name.setBackground(new java.awt.Color(80, 195, 195));
        l_name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(80, 195, 195));

        lec_button.setText("Lecturers");
        lec_button.setPreferredSize(new java.awt.Dimension(120, 50));
        lec_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lec_buttonActionPerformed(evt);
            }
        });

        subj_button.setText("Subjects");
        subj_button.setPreferredSize(new java.awt.Dimension(120, 50));
        subj_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj_buttonActionPerformed(evt);
            }
        });

        stud_button.setText("Students");
        stud_button.setPreferredSize(new java.awt.Dimension(120, 50));
        stud_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_buttonActionPerformed(evt);
            }
        });

        loc_button.setText("Locations");
        loc_button.setPreferredSize(new java.awt.Dimension(120, 50));
        loc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Statistics");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lec_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subj_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stud_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loc_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(lec_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subj_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stud_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loc_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(80, 195, 195));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(374, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lec_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lec_buttonActionPerformed
        // TODO add your handling code here:
        l_name.setText("Lectures");
        jTabbedPane1.removeAll();
        jTabbedPane1.add(lec);
    }//GEN-LAST:event_lec_buttonActionPerformed

    private void subj_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj_buttonActionPerformed
        // TODO add your handling code here:
        l_name.setText("Subjects");
        jTabbedPane1.removeAll();
        jTabbedPane1.add(sub);
    }//GEN-LAST:event_subj_buttonActionPerformed

    private void loc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_buttonActionPerformed
        // TODO add your handling code here:
        l_name.setText("Locations");
        jTabbedPane1.removeAll();
        jTabbedPane1.add(loc);
    }//GEN-LAST:event_loc_buttonActionPerformed

    private void stud_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_buttonActionPerformed
        // TODO add your handling code here:
        l_name.setText("Student");
        jTabbedPane1.removeAll();
        jTabbedPane1.add(stud);
    }//GEN-LAST:event_stud_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l_name;
    private javax.swing.JButton lec_button;
    private javax.swing.JButton loc_button;
    private javax.swing.JButton stud_button;
    private javax.swing.JButton subj_button;
    // End of variables declaration//GEN-END:variables


private void sub_count(){
         try {
             ResultSet rs = dbclass.search("SELECT COUNT(Code) AS x FROM subdetails");
             if (rs.next()) {
                 int i = Integer.parseInt(rs.getString("x"));
                 subj_button.setText("Subjects  ("+i+")");
             }
         } catch (Exception e) {
         }
    }
     private void lec_count(){
         try {
             ResultSet rs = dbclass.search("SELECT COUNT(ID) AS x FROM lecdetails");
             if (rs.next()) {
             int i = Integer.parseInt(rs.getString("x"));
             lec_button.setText("Lecturers  ("+i+")");    
             }
         } catch (Exception e) {
         }
     }
     private void location_count(){
         try {
             ResultSet rs = dbclass.search("SELECT COUNT(location_id) AS x FROM location");
             if (rs.next()) {
                 int i = Integer.parseInt(rs.getString("x"));
                 loc_button.setText("Locations  ("+i+")");
             }
         } catch (Exception e) {
         }
     }

     private void student_count(){
         try {
             ResultSet rs = dbclass.search("SELECT COUNT(student_id) AS x FROM student");
             if (rs.next()) {
                 int i = Integer.parseInt(rs.getString("x"));
                 stud_button.setText("Student  ("+i+")");
             }
         } catch (Exception e) {
         }
     }

}